# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Astgen < Formula
  desc "Generates abstract syntax tree (AST) of project source code"
  homepage "https://github.com/grahambrooks/astgen"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.10.1/astgen-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "21da5cd365e1ea1e576e4d037f52983a17853df0b5fe1ee1a518725b117c5e20"
    end
    on_intel do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.10.1/astgen-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "501c0bc8f0d29659f659069edf709f1d9b5c70377185e08ddc2b09394de4ae28"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.10.1/astgen-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f98b609e244f24afde281d2a07b3b99c06fbf6c8773a41705297555ce8f5e721"
    end
    on_intel do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.10.1/astgen-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "657b0ccd68159691a5c1e1eb16ed458ad526824bacedcdddfcdda04959281f58"
    end
  end

  def install
    bin.install "astgen"
  end

  test do
    assert_path_exists bin/"astgen"
  end
end
