# Generated by scripts/release.py (release-kit) from the v2026.9.0 release — do not edit.
class Astgen < Formula
  desc "Generates abstract syntax tree (AST) of project source code"
  homepage "https://github.com/grahambrooks/astgen"
  version "2026.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.9.0/astgen-v2026.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "a268bb85de0ce1dee2c79992e488e7547e6e9ebcd722f1c919edf0f91e19c088"
    end
    on_intel do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.9.0/astgen-v2026.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "729516cc323a8f0acc6cee6a58487ebcabba17f13b81e0d92701548a3aba3604"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.9.0/astgen-v2026.9.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8bf7764064036e3fa8ca3644e0f93d7820f4ac6ab03438293045aeb601afb071"
    end
    on_intel do
      url "https://github.com/grahambrooks/astgen/releases/download/v2026.9.0/astgen-v2026.9.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a19280f1594e9473599667a4c6802b2ca9d8a2aa8ab95d2c2fb4d53bf933d018"
    end
  end

  def install
    bin.install "astgen"
  end

  test do
    assert_path_exists bin/"astgen"
  end
end
